[package]
name = "force_derive"
version = "0.0.0"
authors = ["Fraser Balch <farseer.ulwithy@gmail.com>"]
keywords = ["proc_macro", "procmacro"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1"
proc-macro2 = "1"
syn = { version = "1", features = ["full"] }

